// src/components/Input/Input.tsx
import type { ChangeEventHandler, InputHTMLAttributes, ReactNode } from 'react';
import { useEffect, useState, useId } from 'react';
import clsx from 'clsx';

type Props = InputHTMLAttributes<HTMLInputElement> & {
  label?: string;
  prefix?: ReactNode;
  suffix?: ReactNode;
};

export const Input = ({
  label,
  prefix,
  suffix,
  maxLength,
  ...props
}: Props) => {
  const id = useId();
  const [characterCount, setCharacterCount] = useState<number>(
    props.defaultValue?.toString().length ?? 0,
  );

  useEffect(() => {
    if (props.value) setCharacterCount(props.value.toString().length);
  }, [props.value]);

  const handleInput: ChangeEventHandler<HTMLInputElement> = (e) => {
    setCharacterCount(e.target.value.length);
  };

  return (
    <>
      {label && (
        <label className="font-medium" htmlFor={id}>
          {label}
        </label>
      )}

      <div className="flex flex-col">
        <div className="flex rounded-lg bg-foreground px-4 py-2 text-base font-semibold ring-neutral-500 focus-within:ring-2">
          {prefix && <span className="flex items-center">{prefix}</span>}
          <input
            id={id}
            className="w-full bg-transparent focus:outline-none"
            onInput={handleInput}
            maxLength={maxLength}
            {...props}
          />
          {suffix && <span className="flex items-center">{suffix}</span>}
        </div>

        {maxLength && (
          <span
            className={clsx(
              'text-end text-xs',
              characterCount > maxLength && 'font-semibold text-red-400',
            )}
          >
            {characterCount}/{maxLength}
          </span>
        )}
      </div>
    </>
  );
};

// src/components/base/Input/Input.vue
<script lang="ts" setup>
import { computed, ref, useAttrs, watch } from 'vue';

interface Props {
  name?: string;
  description?: string;
  validation?: string | null;
  label?: string;
  prefix?: string;
}

const props = defineProps<Props>();

interface Emits {
  (event: 'input', value: string): void;
}

const emit = defineEmits<Emits>();

const attrs = useAttrs();
const value = ref(attrs.value ?? '');

const handleInput = (e: Event) => {
  emit('input', (e.target as HTMLInputElement).value);
};

const ariaValue = computed(() => `${props.prefix}${value.value}`);
</script>

<template>
  <label v-if="label" :for="name" class="text-lg font-bold text-neutral-400">{{ label }}</label>
  <div
    class="py-2 px-4 w-full rounded-lg bg-bodySecundary text-white text-lg font-bold placeholder:text-neutral-600 flex items-center"
    :class="{ 'mt-1': label }"
  >
    <span v-if="prefix">{{ prefix }}</span>
    <input
      :aria-label="name"
      :aria-valuetext="ariaValue"
      :name="name"
      v-model="value"
      @input="handleInput"
      class="w-full bg-transparent focus:outline-none"
    />
  </div>
  <p v-if="validation" class="mt-2 text-sm font-bold text-red-500">
    {{ validation }}
  </p>
  <p v-else class="mt-2 text-sm font-bold text-neutral-400">
    {{ description }}
  </p>
</template>
