// src/pages/Redeem/Redeem.vue
<template>
  <Header />
  <Container>
    <h2 class="mb-5">Redeem a Plus coupon</h2>

    <input
      placeholder="XXXX-XXXX-XXXX"
      @input="code = ($event.target as any)?.value"
      :value="code"
      class="w-full rounded-2xl bg-bodySecundary p-4 text-3xl font-bold uppercase tracking-[0.15em]"
    />

    <Button @click="routeToCode" :disabled="isContinueButtonDisabled" class="mt-5">{{
      t('buttons.continue')
    }}</Button>
  </Container>
</template>

<script lang="ts" setup>
import { ref, watch } from 'vue';

import Header from '~/components/layout/Header.vue';
import Container from '~/components/layout/Container.vue';
import Button from '~/components/base/Button.vue';
import { useI18n } from 'vue-i18n';
import { useRouter } from 'vue-router';

const { t } = useI18n();
const router = useRouter();

const isContinueButtonDisabled = ref(true);
const code = ref('');

const segmentChars = 4;
const segmentCount = 3;
const totalCharLength = segmentChars * segmentCount + (segmentCount - 1);

watch(code, (newCode, oldCode) => {
  if (newCode.length == totalCharLength) {
    isContinueButtonDisabled.value = false;
  }

  if (newCode.length > 0) {
    if (!newCode[newCode.length - 1].match(/^[a-z0-9]+$/i)) {
      newCode = newCode.slice(0, newCode.length - 1);
    }
  }

  if (newCode.length > 0) {
    if (newCode.length < totalCharLength) {
      isContinueButtonDisabled.value = true;
    }

    if (newCode.length % (segmentChars + 1) == 0) {
      if (newCode.length >= oldCode.length) {
        newCode = newCode.slice(0, newCode.length - 1) + '-' + newCode[newCode.length - 1];
      } else {
        newCode = newCode.slice(0, newCode.length - 1);
      }
    }
  }

  code.value = newCode.substring(0, totalCharLength);
});

const routeToCode = () => {
  const parsed = code.value.split('-').join('');
  router.push({ name: 'RedeemCode', params: { code: parsed } });
};
</script>

// src/pages/redeem/index.tsx
import { Button } from '@/components/Button';
import { Container } from '@/components/Container';
import { Title } from '@/components/Title';
import { useToaster } from '@/hooks';
import type { SSRProps } from '@/utils/ssrUtils';
import { fetchUser } from '@/utils/ssrUtils';
import type { GetServerSideProps, NextPage } from 'next';
import { useRouter } from 'next/router';
import { useCallback, useState } from 'react';

export const getServerSideProps: GetServerSideProps<SSRProps> = async (ctx) => {
  const user = await fetchUser(ctx);

  return {
    props: {
      user,
    },
  };
};

const RedeemPage: NextPage = () => {
  const router = useRouter();
  const [couponCode, setCouponCode] = useState('');
  const toaster = useToaster();

  const setCouponCallback = (value: string) => {
    const cleanCode = value.replaceAll('-', '');
    const trimmed = cleanCode.slice(0, 12);
    setCouponCode(trimmed.match(/.{1,4}/g)!.join('-'));
  };

  const continueRedeem = useCallback(() => {
    const cleanCode = couponCode.replaceAll('-', '');

    if (cleanCode.length === 12) router.push(`/redeem/${cleanCode}`);
    else toaster.error('Invalid coupon code');
  }, [couponCode]);

  return (
    <Container className="pt-20">
      <Title>Redeem</Title>
      <h1>Redeem a Plus coupon</h1>
      <input
        type="text"
        value={couponCode}
        onChange={(e) => setCouponCallback(e.target.value)}
        placeholder="XXXX-XXXX-XXXX"
        className="my-5 w-full rounded-2xl bg-foreground p-4 text-lg font-bold uppercase tracking-[0.15em]"
      />
      <Button onClick={continueRedeem}>continue</Button>
    </Container>
  );
};

export default RedeemPage;
