// src/components/Footer.tsx
import Link from 'next/link';
import { event } from 'nextjs-google-analytics';
import { Container } from './Container';
import { StoreBadge } from './StoreBadges';

const links: { label: string; links: { label: string; href: string }[] }[] = [
  {
    label: 'stats.fm',
    links: [
      {
        label: 'Home',
        href: '/',
      },
      {
        label: 'Support',
        href: 'https://support.stats.fm/',
      },
      {
        label: 'Beta program',
        href: '/beta',
      },
    ],
  },
  {
    label: 'Socials',
    links: [
      {
        label: 'Discord',
        href: 'https://stats.fm/discord',
      },
      {
        label: 'Twitter',
        href: 'https://twitter.com/spotistats',
      },
      {
        label: 'Instagram',
        href: 'https://www.instagram.com/statsfm/',
      },
    ],
  },
  {
    label: 'Legal',
    links: [
      {
        label: 'Privacy',
        href: '/privacy',
      },
      {
        label: 'Terms',
        href: '/terms',
      },
    ],
  },
];

export const Footer = () => {
  return (
    <Container as="footer" className="py-14">
      <div className="grid grid-cols-2 place-items-start gap-4 md:grid-cols-4">
        {links.map((cat, i) => (
          <div key={i} className="grid place-items-start">
            <h4 className="mb-2 text-text-grey">{cat.label}</h4>
            <ul className="grid gap-2">
              {cat.links.map((link, i) => (
                <li key={i}>
                  <Link href={link.href} className="text-[1rem]">
                    <a
                      onClick={
                        cat.label === 'Socials'
                          ? () =>
                              event(`FOOTER_${link.label.toLowerCase()}_click`)
                          : undefined
                      }
                    >
                      {link.label}
                    </a>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        ))}

        <div>
          <h4 className="text-neutral-400">Download</h4>
          <div className="mt-4"></div>
          <StoreBadge
            store="apple"
            size="xs"
            onClick={() => event('FOOTER_appstore')}
          />
          <div className="mt-2"></div>
          <StoreBadge
            store="google"
            size="xs"
            onClick={() => event('FOOTER_playstore')}
          />
        </div>
      </div>

      <br />
      <br />

      {/* <p className="min-w-full text-center text-sm text-neutral-500 md:order-1">
        All copyrighted content (i.e. album artwork) on stats.fm are owned by
        their respective owners. Data is provided by Spotify AB and Apple
        Music®. stats.fm is in no way affiliated with Spotify AB or Apple
        Music®.
      </p> */}
      <p className="min-w-full text-center text-sm text-neutral-500 md:order-1">
        All copyrighted content (i.e. album artwork) on stats.fm are owned by
        their respective owners. Data is provided by Spotify AB. stats.fm is in
        no way affiliated with Spotify AB.
      </p>
      <p className="min-w-full text-center md:mt-0">
        © 2022 StatsFM B.V. (formerly Spotistats for Spotify). All rights
        reserved. Made with ❤️ in the Netherlands.
      </p>
    </Container>
  );
};

// src/components/layout/Footer.vue
<template>
  <Container class="pt-14 pb-14">
    <div class="font-bold xl:grid xl:gap-8">
      <div class="grid grid-cols-2 gap-8 md:grid-cols-4">
        <div v-for="(link, index) in links" :key="index">
          <h4 class="text-neutral-400">{{ link.label }}</h4>
          <ul class="mt-2 space-y-2">
            <li v-for="(link, index) in link.links" :key="index">
              <Link :to="link.to" class="text-[1rem]">{{ link.label }}</Link>
            </li>
          </ul>
        </div>

        <div>
          <h4 class="text-neutral-400">Download</h4>
          <div class="mt-4"></div>
          <a
            class="h-9"
            href="https://apps.apple.com/app/spotistats-for-spotify/id1526912392"
            target="blank"
            ><img src="../../assets/apple_appstore_badge.png" alt="Apple Appstore" class="h-9" />
          </a>
          <div class="mt-2"></div>
          <a
            class="h-9"
            href="https://play.google.com/store/apps/details?id=dev.netlob.spotistats"
            target="blank"
            ><img src="../../assets/google_play_badge.png" alt="Google Play" class="h-9" />
          </a>
        </div>
      </div>
    </div>
    <p class="mt-10 min-w-full pt-10 text-center text-neutral-500 md:order-1 md:mt-0">
      All copyrighted content (i.e. album artwork) on Stats.fm are owned by their respective owners.
      Data is provided by Spotify. Spotify is a trademark of Spotify AB. Stats.fm is in no wayaffiliated with Spotify.
    </p>
    <p class="mt-10 min-w-full pt-5 text-center md:order-1 md:mt-0">
      © 2022 Stats.fm / Spotistats for Spotify. All rights reserved. Made with ❤️ in the
      Netherlands.
    </p>
  </Container>
</template>

<script lang="ts" setup>
import Container from '../layout/Container.vue';
import Button from '../base/Button.vue';
import Link from '../base/Link.vue';
import { LocationAsRelativeRaw, useRouter } from 'vue-router';
import { onBeforeMount } from 'vue';

const router = useRouter();

const links: { label: string; links: { label: string; to: string | LocationAsRelativeRaw }[] }[] = [
  {
    label: 'Stats.fm',
    links: [
      {
        label: 'Home',
        to: { name: 'Home' }
      },
      {
        label: 'Support',
        to: 'https://support.stats.fm/'
      },
      {
        label: 'Beta program',
        to: { name: 'Beta' }
      }
    ]
  },
  {
    label: 'Socials',
    links: [
      {
        label: 'Discord',
        to: 'https://discord.gg/spotistats'
      },
      {
        label: 'Twitter',
        to: 'https://twitter.com/spotistats'
      },
      {
        label: 'Instagram',
        to: 'https://instagram.com/spotistats'
      }
    ]
  },
  {
    label: 'Legal',
    links: [
      {
        label: 'Privacy',
        to: { name: 'Privacy' }
      },
      {
        label: 'Terms',
        to: { name: 'Terms' }
      }
    ]
  }
];
</script>
