// src/components/Textarea/Textarea.tsx
import type { FormEventHandler, TextareaHTMLAttributes } from 'react';
import { useEffect, useState, useId } from 'react';
import clsx from 'clsx';

interface Props extends TextareaHTMLAttributes<HTMLInputElement> {
  label?: string;
  resize?: 'both' | 'horizontal' | 'vertical' | 'none';
}

export const Textarea = ({
  label,
  maxLength,
  resize = 'vertical',
  ...props
}: Props) => {
  const id = useId();
  const [characterCount, setCharacterCount] = useState<number>(
    props.defaultValue?.toString().length ?? 0
  );

  useEffect(() => {
    if (props.value) setCharacterCount(props.value.toString().length);
  }, [props.value]);

  const handleInput: FormEventHandler<HTMLTextAreaElement> = (e) => {
    // @ts-ignore TODO: add type checking
    setCharacterCount(e.target.value.length);
  };

  return (
    <>
      {label && (
        <label className="font-medium" htmlFor={id}>
          {label}
        </label>
      )}

      <div className="flex flex-col">
        <textarea
          id={id}
          className="flex rounded-lg bg-foreground p-4 font-semibold ring-neutral-500 focus:outline-none focus:ring-2"
          style={{ resize }}
          // @ts-ignore
          onInput={handleInput}
          maxLength={maxLength}
          {...props}
        />

        {maxLength && (
          <span
            className={clsx(
              'text-end text-xs',
              characterCount > maxLength && 'font-semibold text-red-400'
            )}
          >
            {characterCount}/{maxLength}
          </span>
        )}
      </div>
    </>
  );
};

// src/components/base/Textarea.vue
<template>
  <div class="flex flex-col items-end">
    <textarea
      @input="onInput"
      :value="value"
      :style="{ resize: isResizeable ? 'vertical' : 'none' }"
      :placeholder="placeholder"
      :maxlength="maxLength"
      class="bg-bodySecundary rounded-2xl p-5 w-full focus:outline-none"
    ></textarea>
    <span v-if="maxLength" class="text-xs text-textGrey font-bold"
      >{{ charCount }}/{{ maxLength }}</span
    >
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';

const emit = defineEmits(['input']);
defineProps<{
  placeholder?: string;
  isResizeable?: boolean;
  value?: string;
  maxLength?: number;
}>();

const charCount = ref(0);

const onInput = (e: any) => {
  const value = e.target.value;

  charCount.value = value.length;
  emit('input', value);
};
</script>
