// src/components/base/Coupon.vue
<template>
  <Card
    class="max-w-max cursor-pointer pb-2 pt-5"
    @click="router.push({ name: 'GiftCoupon', params: { code: giftcode.code } })"
  >
    <Badge @click="copyRedeemCode" class="w-full cursor-pointer">{{
      formatCode(giftcode.code)
    }}</Badge>
    <p v-if="giftcode.claimedDate" class="mt-3 text-center">
      Claimed {{ dayjs(giftcode.claimedDate).fromNow() }} by
      <Link
        :to="{ name: 'User', params: { userId: giftcode.boughtBy.id } }"
        class="font-bold text-white"
        >{{ giftcode.boughtBy.displayName }}</Link
      >
    </p>
    <p v-else class="mt-3 text-center">
      {{ t('coupon.purchased') }} {{ dayjs(giftcode.purchaseDate).fromNow() }}
    </p>
  </Card>
</template>

<script lang="ts" setup>
import { defineProps } from 'vue';

import Card from '~/components/layout/Card.vue';
import Link from '~/components/base/Link.vue';
import Badge from '~/components/base/Badge.vue';

import { useI18n } from 'vue-i18n';
import { useStore } from '~/store';
import { GiftCode } from '~/types';
import dayjs from '~/dayjs';
import { useRouter } from 'vue-router';

const props = defineProps<{
  giftcode: GiftCode;
}>();

const { t } = useI18n();
const router = useRouter();

const formatCode = (code: string) => {
  return code.match(new RegExp('.{1,4}', 'g'))!.join('-');
};

const copyRedeemCode = () => {
  navigator.clipboard.writeText(props.giftcode.code);
};
</script>

// src/components/gift/Coupon.tsx
import type { GiftCode } from '@/types/gift';
import dayjs from '@/utils/dayjs';
import Link from 'next/link';
import type { FC } from 'react';
import { useState } from 'react';
import { CouponModal } from './CouponModal';

export const Coupon: FC<{ giftcode: GiftCode }> = ({ giftcode }) => {
  const [open, setOpen] = useState(false);

  return (
    <div
      className="max-h-max max-w-max rounded-2xl bg-bodySecundary p-5"
      onClick={() => {
        console.log('asd');
        setOpen(true);
      }}
    >
      <span
        className="w-max cursor-pointer select-none rounded-xl bg-primary/10 py-1 px-4 font-bold text-primary"
        onClick={() => navigator.clipboard.writeText(giftcode.code)}
      >
        {giftcode.code}
      </span>
      {giftcode.claimedAt ? (
        <p className="mt-3 text-center">
          Claimed {dayjs(giftcode.claimedAt).fromNow()} by{' '}
          <Link href={`/user/${giftcode.claimedBy.id}`}>
            <a className="font-bold text-white hover:opacity-70">
              {giftcode.claimedBy.displayName}
            </a>
          </Link>
        </p>
      ) : (
        <p className="mt-3 mb-0 text-center">
          Purchased {dayjs(giftcode.purchasedAt).fromNow()}
        </p>
      )}
      <CouponModal
        open={open}
        onClose={() => setOpen(false)}
        giftCode={giftcode}
      />
    </div>
  );
};
