// src/components/base/Chip/Chip.tsx
import { FC, LiHTMLAttributes } from 'vue';

interface Props extends LiHTMLAttributes {}

const Chip: FC<Props> = (props, { slots }) => (
  <li class="h-max w-max rounded-full bg-bodySecundary px-4 py-2 font-medium text-white" {...props}>
    {slots.default && slots.default()}
  </li>
);

export default Chip;

// src/components/Chip/Chip.tsx
import type { HTMLAttributes, PropsWithChildren } from 'react';

interface Props extends HTMLAttributes<HTMLLIElement> {}

const Chip = ({ children, ...props }: PropsWithChildren<Props>) => (
  <li
    className="h-max w-max whitespace-nowrap rounded-full bg-foreground px-4 py-2 font-medium text-white"
    {...props}
  >
    {children}
  </li>
);

export default Chip;
