// src/components/base/Chip/ChipGroup.vue
<template>
  <div
    class="flex gap-2 flex-nowrap overflow-x-auto"
    @wheel.prevent="onWheelScroll"
    ref="chipgroup"
  >
    <slot />
  </div>
</template>

<script lang="ts" setup>
import { Ref, ref } from 'vue';

const chipgroup: Ref<HTMLDivElement | undefined> = ref();

const onWheelScroll = (e: WheelEvent) => {
  if (chipgroup.value) {
    chipgroup.value.scrollLeft += e.deltaY || e.deltaX; // deltaX for trackpads
  }
};
</script>

// src/components/Chip/ChipGroup.tsx
import clsx from 'clsx';
import type {
  HTMLAttributes,
  PropsWithChildren,
  WheelEventHandler,
} from 'react';
import { useRef } from 'react';

interface Props extends HTMLAttributes<HTMLUListElement> {}

const ChipGroup = ({ children, ...props }: PropsWithChildren<Props>) => {
  const ref = useRef<HTMLUListElement>(null);

  const handleWheelScroll: WheelEventHandler = (e) => {
    if (ref.current) ref.current.scrollLeft += e.deltaY || e.deltaX; // deltaX for trackpads
  };

  return (
    <ul
      className={clsx(
        'flex flex-nowrap gap-2 overflow-x-auto',
        props.className
      )}
      onWheel={handleWheelScroll}
      ref={ref}
      {...props}
    >
      {children}
    </ul>
  );
};

export default ChipGroup;
