// src/components/base/Avatar/Avatar.tsx
import { computed, FC, ImgHTMLAttributes } from 'vue';
import { Image } from '../Image';

type Size = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl';
export type AvatarSize = Size;

interface Props extends ImgHTMLAttributes {
  name: string;
  size?: Size;
}

export const sizes: Record<Size, string> = {
  xs: 'w-6',
  sm: 'w-8',
  md: 'w-12',
  lg: 'w-16',
  xl: 'w-24',
  '2xl': 'w-32',
  '3xl': 'w-40',
  '4xl': 'w-48'
};

const Avatar: FC<Props> = ({ name, size = 'md', ...props }, { slots }) => {
  const initials = computed(() => {
    return name
      .match(/(\b\S)?/g)!
      .join('')
      .match(/(^\S|\S$)?/g)!
      .join('')
      .toUpperCase();
  });

  return (
    <div class="relative">
      <Image
        // webkit aspect ratio issue
        class={['aspect-square select-none rounded-full pt-[100%] shadow-sm', sizes[size]]}
        {...props}
      >
        {{
          loading: () => (
            <span class={'text-fontSecundary animation-pulse font-medium'}>{initials.value}</span>
          ),
          unavailable: () => <span class={'font-medium'}>{initials.value}</span>
        }}
      </Image>

      <div class="absolute bottom-0 right-0">{slots.default && slots.default()}</div>
    </div>
  );
};

export default Avatar;

// src/components/Avatar/Avatar.tsx
import clsx from 'clsx';
import { Image } from '@/components/Image';
import type { PropsWithChildren } from 'react';
import { DEFAULT_USER_IMAGE_URL } from '@/constants';
import { isFacebookURL } from '@/utils/urls';

export type AvatarSize =
  | 'xs'
  | 'sm'
  | 'md'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | '4xl';

interface Props {
  name: string;
  size?: AvatarSize;
  src?: string;
}

export const sizes: Record<AvatarSize, number> = {
  xs: 24,
  sm: 32,
  md: 48,
  lg: 64,
  xl: 96,
  '2xl': 128,
  '3xl': 160,
  '4xl': 192,
};

export const Avatar = ({
  name,
  size = 'md',
  src,
  children,
  ...props
}: PropsWithChildren<Props>) => {
  const initials = name
    .match(/(\b\S)?/g)!
    .join('')
    .match(/(^\S|\S$)?/g)!
    .join('')
    .toUpperCase();

  if (!src) {
    return (
      <div
        className="relative grid aspect-square shrink-0 place-items-center rounded-full bg-foreground"
        style={{ width: sizes[size] }}
      >
        <p>{initials}</p>

        <div className="absolute bottom-0 right-0">{children}</div>
      </div>
    );
  }

  return (
    <div
      className="relative shrink-0"
      style={{ width: sizes[size], height: sizes[size] }}
    >
      <Image
        // eslint-disable-next-line tailwindcss/no-custom-classname
        className={clsx(
          'aspect-square bg-foreground object-cover text-center text-neutral-400',
          `leading-[${sizes[size]}px]`,
        )}
        rounded
        width={sizes[size]}
        height={sizes[size]}
        alt={initials}
        src={isFacebookURL(src) ? DEFAULT_USER_IMAGE_URL : src}
        {...props}
      />

      <div className="absolute bottom-0 right-0">{children}</div>
    </div>
  );
};
